use serde::Deserialize;
use std::collections::HashMap;

#[derive(Deserialize, Debug)]
pub struct User {
    pub about: String,
    pub activity_visible: bool,
    pub avatar_urls: HashMap<String, Option<String>>,
    pub can_ban: bool,
    pub can_converse: bool,
    pub can_edit: bool,
    pub can_follow: bool,
    pub can_ignore: bool,
    pub can_post_profile: bool,
    pub can_view_profile: bool,
    pub can_view_profile_posts: bool,
    pub can_warn: bool,
    pub custom_title: String,
    pub email: String,
    pub email_on_conversation: bool,
    pub gravatar: String,
    pub is_admin: bool,
    pub is_discouraged: bool,
    pub is_moderator: bool,
    pub is_staff: bool,
    pub is_super_admin: bool,
    pub last_activity: u64,
    pub location: String,
    pub message_count: u64,
    pub profile_banner_urls: HashMap<String, Option<String>>,
    pub push_on_conversation: bool,
    pub reaction_score: u64,
    pub secondary_group_ids: Vec<u64>,
    pub show_dob_date: bool,
    pub show_dob_year: bool,
    pub signature: String,
    pub timezone: String,
    pub usa_tfa: bool,
    pub user_group_id: u64,
    pub user_id: u64,
    pub user_state: String,
    pub user_title: String,
    pub username: String,
    pub view_url: String,
    pub visible: bool,
    pub vote_score: u64,
    pub website: String,
}
